import type { NextPage } from "next";
import Head from "next/head";
import Hero from "@components/Header/hero";
import Article from "@components/article";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | CDHO </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Article />
    </div>
  );
};

export default Home;
